### ISSUE TITLE
Python3 Jpeg Toolbox

### ISSUE THREAD

**Issue by asrabon** [YassineYousfi/alaska#3]
I am having issues installing/compiling the JPEG Toolbox on my Windows 10 machine despite having all dependencies. Is there any way you could build wheel packages for the toolbox or if there is requirements that aren't listed I might not have installed.

**Comment by YassineYousfi** [comment]
You will need to compile the JPEG toolbox for windows on your end ... I don't have any windows environment to provide a windows package. Added System requirements (linux and macOS) in the README. Sorry for the inconvenience.

**Comment by YassineYousfi** [comment]
Closing for now.
