### ISSUE TITLE
"ALASKA steganalaysis challenge" link in readme file throws error

### ISSUE THREAD

**Issue by jcatanza** [YassineYousfi/alaska#4]
http://alaska.utt.fr/alaska1 link throws 502 Bad Gateway Error

**Comment by YassineYousfi** [comment]
It seems that the Alaska competition organizers took off the datasets of Alaska V1 from the website. The datasets of Alaska V2 can be found on kaggle: https://www.kaggle.com/c/alaska2-image-steganalysis/data

**Comment by YassineYousfi** [comment]
Thanks for pointing this out, updated README
