### ISSUE TITLE
[Jpeglib] Code crash when call  jpeglib.jpeg

### ISSUE THREAD

**Issue by lampts** [YassineYousfi/alaska#6]
After cloning the repo, I've compiled jpeglib on MacOS. I can import tools.python3_jpeg_toolbox as jpeglib. However when testing to call jpeglib.jpeg("temp.jpg"), I got the crash. Did you face it as well?

**Comment by YassineYousfi** [comment]
Can you use: https://github.com/dwgoon/jpegio ?
You will need to change line 39 in src/tools/jpeg_utils.py to
```python
Q = S.quant_tables[S.comp_info[i].quant_tbl_no] 
```
I will update the repo using jpegio when I have time.

**Comment by lampts** [comment]
Thanks for the information.
